# Generated by Django 3.2.3 on 2021-05-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acupet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(max_length=251),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_name',
            field=models.CharField(max_length=251),
        ),
        migrations.AlterField(
            model_name='pet',
            name='description',
            field=models.CharField(max_length=501),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_name',
            field=models.CharField(max_length=251),
        ),
    ]
